from transformers import GPT2Tokenizer, GPT2LMHeadModel, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import Dataset

pairs = [
    ("Ada ya mja hunena muungwana ni kitendo.", "Tabia ya mtu inaonyesha kama yeye ni muungwana."),
    ("Adhabu ya kaburi aijuaye maiti.", "Watu waliofarijika ni waliokufa pekee ndio wajua adhabu ya kaburi."),
    ("Adui wa mtu ni mtu, adui mpende, adui aangukapo mnyanyue.", "Adui pia ni binadamu; mpe hata adui yako upendo na kumsaidia akinang'oka."),
    ("Afadhali ya Musa kuliko ya Firauni.", "Ni bora kuwa maskini kuliko kuwa tajiri ukihisi haba."),
    ("Afya ni bora kuliko mali.", "Afya ni muhimu kuliko utajiri."),
    ("Ahadi ni deni.", "Ahadi ni sawa na deni."),
    ("Aibu ya maiti aijuaye mwosha.", "Yeye anayemfumbua maiti ndiye ajuaye aibu yake."),
    ("Aisifuye mvua imemnyea.", "Aliyemsifu mvua alionywa kwa kuangaziwa na mvua."),
    ("Alisifuye jua limemwangaza.", "Aliyemsifu jua alimwangaza."),
    ("Ajali haina kinga.", "Ajali haiwezi kuzuiwa kabisa."),
    ("Ajizi ni nyumba ya njaa.", "Uzembe ni nyumba ya njaa."),
    ("Akiba halozi, akiba si mbi ijapokuwa ya kumbi, siku ya kivumbi hutiwa motoni.", "Akiba ni nzuri hata ikiwa ni ndogo; itakuja kukusaidia wakati wa dharura."),
    ("Akili ni mali, akili nyingi huondoa maarifa.", "Akili ni mali; maarifa kupita kiasi yanaweza kuondoa ufahamu."),
    ("Akili ni nywele kila mtu ana zake.", "Kila mtu ana akili yake mwenyewe."),
    ("Akili nyingi huondoa maarifa.", "Maarifa nyingi kupita kiasi yanaweza kuondoa ufahamu."),
    ("Akufaaye kwa dhiki ndiye rafiki.", "Rafiki wa kweli ni yule anayekuwepo wakati wa shida."),
    ("Akutendaye mtende, mche asiyekutenda.", "Mtu akutendaye wema mlete wema; asiyetenda wema msijali."),
    ("Aliye juu mngoje chini.", "Aliyeko juu hatimaye atashushwa chini."),
    ("Aliye kando haangukiwi na mti.", "Aliyekaa mbali na mti hatangushwi na mti."),
    ("Aliyekula kitovu chako hatakuachia utumbo.", "Aliyekula kitovu chako hatakuacha njia za kunufaika na wewe."),
    ("Aliyekunyima kunde/mbaazi amekupungunguzia mashuzi.", "Aliyekunyima kunde amepunguza mpishi wako."),
    ("Aliyekunyoa shungi kakupunguzia kuchana.", "Aliyekunyoa nywele zako amekufanyia kazi ya kusafisha."),
    ("Aliyetota hajui kutota.", "Aliyetoka hajui jinsi ya kutenda katika hali hiyo."),
    ("Aliyeumawa na nyoka akiona unyasi hushituka.", "Aliyebebwa na tukio la kujeruhiwa hushituka hata kwa kitu kidogo."),
    ("Amani haipatikani ila kwa ncha ya upanga.", "Amani inaweza kuonekana kuwa inatokana na nguvu au vurugu."),
    ("Amnyimaye punda adesi ampunguzia mashuzi.", "Aliyekunyima punda adesi amepunguza mzigo wake."),
    ("Anayemwamini Mungu si mtovu.", "Aneye kumwamini Mungu si mtu mwovu."),
    ("Angalipaa juu kipungu kamwe hafiki mbinguni.", "Msokoto mdogo hata ukiruka juu hautafika mbinguni."),
    ("Angurumapo Simba, mcheza nani?", "Nani atamwambia simba linapomaliza kunguruma? (Nani atakabiliana naye?)"),
    ("Asio mali, hasidi wa mwenye mali.", "Asiye na mali huming'ang'ania mwenye mali."),
    ("Asiye na bahati habahatiki.", "Yeye asiye na bahati hawezi kufanikiwa kwa bahati."),
    ("Asiye na mwana aeleke jiwe.", "Asiye na mtoto apokee jiwe (tamani isiyoweza kutimizwa)."),
    ("Asiyejua utu si mtu.", "Asiyefahamu utu sio binadamu kwa maana ya huruma/mema."),
    ("Asiyekubali kushindwa si mshindani.", "Asiyekubali kushindwa si mshindani halali."),
    ("Asiyesafiri husifu upishi wa mama yake tu.", "Asiyetembelea ulimwengu wote humshangaa tu upishi wa mama yake."),
    ("Asiyesikia la mkuu huvunjika guu.", "Asiyesikiliza ushauri wa wazee atadharaulika."),
    ("Atangaye na jua hujua.", "Msafiri mwenye uzoefu anajua mengi."),
    ("Avumaye baharini papa kumbe wengine wapo.", "Kukaa tu juu ya bahari si mali ya panya pekee; kuna viumbe wengine pia."),
    ("Awali ni awali hakuna awali mbovu.", "Mwanzoni ni mwanzoni; hakuna mwanzoni mbaya."),
    ("Baada ya dhiki faraja.", "Baada ya shida huja faraja."),
    ("Bahati ya mwenzio usiilalie mlango wazi.", "Usipende bahati ya mwenzako kwa kumfikia kwa tamaa."),
    ("Balaa hukutia mtu wako.", "Masiha hukuta wewe mwenyewe."),
    ("Bandu bandu humaliza gogo.", "Kitu kidogo kidogo kinamaliza kitu kikubwa."),
    ("Baniani mbaya kiatu chake dawa.", "Hata mtu mbaya ana kitu kizuri (kama kiatu kilicho sawa)."),
    ("Bao nene si chuma chembamba.", "Kamba nene sio chuma chembamba."),
    ("Barua ya moyo husomwa juu ya panda la uso.", "Hisia za moyo zinaonekana uso."),
    ("Bendera hufuata upepo.", "Bendera hufuata mwelekeo wa upepo."),
    ("Bilashi, bilashi, katu haitoshi.", "Kidogo kidogo hakitoshi."),
    ("Binadamu ni kama kilihafu hakosi uchafu.", "Mwanadamu ana mapungufu kama chungu lenye uchafu."),
    ("Bura yangu sibadili kwa rehani.", "Sitingeza vitu vyangu kwa rehani kwa wengine."),
    ("Chanda chema huvikwa pete.", "Mtu mwenye tabia njema hupata tuzo."),
    ("Chelewa chelewa, utakuta mwana si wako.", "Uchelewaji hufanya utuache vitu vyako vitoke."),
    ("Chombo kilichopikiwa samaki hakiachi kunuka vumba.", "Chombo kilichopikwa samaki hakisafi; uchezo wake unabaki."),
    ("Chovya chovya humaliza buyu la asali.", "Kula kidogo kidogo kunamaliza asali."),
    ("Chungu kidogo huchemka upesi.", "Chungu kidogo hupika haraka."),
    ("Chururu si ndondondo.", "Tone moja si mafuriko."),
    ("Dalili ya mvua ni mawingu.", "Mawingu ni dalili ya mvua."),
    ("Damu ni nzito kuliko maji.", "Damu ni nzito kuliko maji; damu ina umuhimu zaidi."),
    ("Dau la mnyonge haliendi joshi likienda joshi ni matakwa ya Mungu.", "Boti ya maskini haitokei mbali; ikifanikiwa ni kwa mapenzi ya Mungu."),
    ("Dawa ya deni kulipa.", "Dawa ya deni ni kulilipa."),
    ("Dawa ya jipu kulipasua.", "Dawa kwa jipu ni kulifungua/kulipasua."),
    ("Dawa ya moto ni moto.", "Tiba kwa moto ni moto (kutumia nishati sawa)."),
    ("Debe shinda haliachi kutika.", "Debe lililojaa linaweza kuendelea kukwaruza."),
    ("Debe tupu haliachi kuvuma.", "Debe tupu huendelea kutoa kelele."),
    ("Domo kaya samli kwa mwenye ngombe.", "Mtu mfuataji wa maneno ni baraka kwa mwenye ng’ombe."),
    ("Dondandugu halina dawa.", "Mjeraha usiopona haujapata tiba."),
    ("Dua la kuku halimpati mwewe.", "Dua ya kuku haiwezi kufika kwa mwewe."),
    ("Dunia hadaa ulimwengu shujaa.", "Dunia ni ya ulaghai; ulimwengu ni tofauti."),
    ("Eda ni ada yenye faida.", "Eda ni ada yenye manufaa kwa mke baada ya kifo au talaka."),
    ("Fadhila mpe mama na Mola atakubariki.", "Mfanyie fadhila mama yako na Mungu atakuibariki."),
    ("Fadhila za punda mashuzi.", "Fadhila kutoka kwa punda hazina thamani."),
    ("Fadhili ukitenda usingoje shukrani.", "Fanya wema bila kutegemea shukrani."),
    ("Fahari isiyo na ari haina heri.", "Kiburi bila bidii hakina faida."),
    ("Fimbo ya mbali haiuwi nyoka.", "Fimbo ya mbali haiwezi kumuua nyoka."),
    ("Fumbo mfumbie mjinga mwerevu huling’amua.", "Mtoa fumbo kwa mjinga, mwerevu ndiye ataelewa."),
    ("Funika kombe mwanaharamu apite.", "Funika vyombo ili mwizi apite bila kuona."),
    ("Ganda la muwa la jana chungu kaona kivuno.", "Ganda la muwa la jana linaweza kuwa fahari kwa mdudu."),
    ("Ghururi na binadamu hawaachani.", "Kiburi na binadamu hayatenganiki."),
    ("Ghushi dhahabu na shaba dhambi na dhawabu havighushiki.", "Dahabu feki na shaba si ya thamani kama dhahabu halisi."),
    ("Haba na haba hujaza kibaba.", "Kidogo kidogo hujaza chombo."),
    ("Hadhari kabla ya hatari.", "Tahadhari kabla ya hatari."),
    ("Hakuna bamvua lisilo usubi.", "Hakuna kile kizuri bila dosari kidogo."),
    ("Hakuna marefu yasiyokuwa na ncha.", "Hakuna umbali usio na mwisho."),
    ("Hakuna masika yasiyokuwa na mbu.", "Hakuna msimu wa mvua usiokuwa na mbu."),
    ("Hakuna ziada mbovu.", "Hakuna ziada isiokuwa nzuri."),
    ("Hamadi kibindo ni silaha iliyo mkononi.", "Mpango uliokamilika ni silaha mikononi."),
    ("Hapana maji yasiyo na mawimbi.", "Hakuna maji bila mawimbi."),
    ("Haraka haraka haina baraka.", "Haraka haileti baraka."),
    ("Hasira hasara.", "Hasira inaleta hasara."),
    ("Hasira ya mkizi furahaya mvuvi.", "Hasira ya samaki wa mto ni furaha kwa mvuvi."),
    ("Hatua moja hufupisha safari.", "Hatua moja inapunguza umbali wa safari."),
    ("Heri kujikwaa kidole kuliko ulimi.", "Ni vyema kukosa kidogo na kidole kuliko kukosea kwa kauli."),
    ("Heri mchawi kuliko mtu fitina.", "Ni bora kuwa mchawi kuliko kuwa msababishi wa matatizo."),
    ("Heri nusu shari kuliko shari kamili.", "Ni bora kuwa na nusu ya shida kuliko shida yote moja."),
    ("Hewala! si utumwa.", "Kukubali maneno ya mtu si utumwa."),
    ("Hindi ndiko kwenye nguo na wendao uchi wako.", "Kuna nguo nyingi India lakini bado kuna watu wanaotembea uchi."),
    ("Huenda umaskini ukakaribia ukafiri.", "Utasikia umasikini ukikaribia imani/pamoja."),
    ("Hukutia mtu wako.", "Adui wako huwa karibu nawe."),
    ("Ibilisi wa mtu ni mtu.", "Ibilisi wa mtu ni mtu mwingine."),
    ("Ingiwa na shake.", "Kulia sana (kulia mara kwa mara)."),
    ("Inuka twende ni kwa waaganao.", "Inuka tu; ni kwa wale wanaoagana."),
    ("Ivushayo ni mbovu.", "Kile kilichokusaidia kushinda tatizo kinaweza kuwa kibaya baadae."),
    ("Jambo la ukucha halichukuliwi shoka.", "Kazi ndogo bila shoka haifai kutumia zana kubwa."),
    ("Jaribu huleta fanaka.", "Kujaribu huleta mafanikio."),
    ("Jawabu la kesho andaa leo.", "Andaa leo majibu ya kesho."),
    ("Jawabu wakatiwe na wakatiwe si zani.", "Jibu mara nyingine hupatikana na mara nyingine sio."),
    ("Jimbi wa shamba hawiki mjini.", "Jogoo wa shamba hawatokea mjini."),
    ("Jino likingoka ukubwani halimei tena.", "Jino lililovutwa ukiwa mtu mzima halirudi kucheza."),
    ("Jogoo likiwika lisiwikae kutakucha.", "Hata jogoo akilia au asiwe aki, asubuhi itakuja."),
    ("Jogoo wa shamba hawiki mjini.", "Jogoo wa shamba hawataisha mjini."),
    ("Kafiri akufaaye si Islamu asiyekufaa.", "Mtu asiyeamini ambaye anasaidia ni bora kuliko Msomi wa dini asiyetenda mema."),
    ("Kamba hukatikia pabovu.", "Kamba huvunjika pale palipo dhaifu."),
    ("Katakata pua uunge wajihi.", "Fanya kitu hata kama ni kigumu, itaongeza nafasi yako ya kufanikiwa."),
    ("Katiti ni tamu kingi kina kiembeza.", "Kidogo ni bora; nyingi zinaweza kuleta madhara."),
    ("Kazi mbi si mchezo mwema.", "Kazi mbaya si kazi nzuri."),
    ("Kenda fumbata si kumi nenda uje kesho.", "Kutoshiba na kile ulicho nacho."),
    ("Kichwa cha kuku hakihimili kilemba.", "Mtu wa hadhi ndogo hawezi kubebwa kwa heshima kubwa."),
    ("Kidole kimoja hakivunji chawa.", "Kilichofanywa kwa pamoja hufanikiwa."),
    ("Kifo cha wengi harusi.", "Kifo cha wengi kinaweza kuwa fursa kwa wengine."),
    ("Kila mtoto na koja lake.", "Kila mtoto ana tabia yake ya kipekee."),
    ("Kila mwacha samboye, huenda ali mwanamaji.", "Ayeaye aache kijiji anaweza kuwa mpiga samaki."),
    ("Kila mwamba ngoma,huvutia kwake.", "Mtu wa kwanza kufanya jambo mara nyingi ana manufaa kwake mwenyewe."),
    ("Kila mwamba ngoma, ngozi huivuta kwake.", "Mtu wa kwanza kufanya jambo mara nyingi ana manufaa kwake mwenyewe."),
    ("Kila ndege huruka kwa ubawa wake.", "Kila ndege huruka kwa mabawa yake mwenyewe."),
    ("Kilichoingia mjini si haramu.", "Kilichoingia mjini hakizingatiwi kama haramu."),
    ("Kilimia kikizama kwa jua huzuka kwa mvua, kikizama kwa mvua huzuka kwa jua.", "Kazi inayokithiri inategemea hali za anga; mabadiliko hutokea."),
    ("Kimya kingi kina mshindo mkuu.", "Kimya kikubwa kina maana kubwa."),
    ("Kinyozi hajinyoi akinyoa kujikata.", "Kinyozi hafanyi kazi yake kwa mwenyewe."),
    ("Kinywa ni jumba la maneno.", "Kinywa ni mahali pa maneno mengi."),
    ("Kipya kinyemi ingawa kidondo.", "Mpya ni laini hata ikiwa ni jeneza/jeraha."),
    ("Kisebusebu na kiroho ki papo.", "Watu wengine wanajifanya hawahitaji kitu lakini kwa kweli wanakitaka."),
    ("Kitanda usicholala huwajui kunguni wake.", "Huwezi kujua wadudu wa kitanda usiwe umelala humo."),
    ("Kitegwacho kukitega kwataka ubongo.", "Kazi yoyote inahitaji maarifa na busara."),
    ("Kivuli cha mgude husaidia walio mbali.", "Kivuli cha mti husaidia wale walio mbali."),
    ("Kujikwaa si kuanguka, bali ni kwenda mbele.", "Kujikwaa si kuanguka bali hatua kuelekea mbele."),
    ("Kukopa harusi kulipa matanga.", "Kukopa ni rahisi lakini kulilipa ni jambo la muhimu."),
    ("Kuku havunji yai lake.", "Kuku haivunji yai lake mwenyewe."),
    ("Kuku mgeni zawadi za kunguru.", "Kuku mgeni ni zawadi kwa kunguru."),
    ("Kula kutamu kulima mavune.", "Kula ni tamu, lakini kulima ni kazi ngumu."),
    ("Kula ni vyepesi lakini kulima ngo.", "Kula ni rahisi, lakini kulima ni ngumu."),
    ("Kula uhondo kwataka matendo.", "Kufurahia shangwe kunahitaji vitendo."),
    ("Kulea mimba si kazi kazi kulea mwana.", "Kuchunga mimba si kazi kama kulea mtoto."),
    ("Kunguru mwoga hukimbiza bawa lake.", "Kunguru mwoga hutafuta njia ya kukwepa."),
    ("Kutoa ni moyo si utajiri.", "Kutoa ni moyo, si utajiri."),
    ("Kutoa ni moyo usambe ni utajiri.", "Kutoa ni kutoka moyoni; si lazima uwe tajiri."),
    ("Kuvua si kazi kazi ni magawioni.", "Kuvua ni moja; kazi ya kweli ni masoko/ugawaji."),
    ("Kuvuja kwa pakacha nafuu kwa mchukuzi.", "Kuvuja kwa mfuko kunamfaa mchukuzi."),
    ("Kuzima koleo si mwisho wa uhunzi.", "Kupumzika si kumaliza kazi."),
    ("Kwa mwari kwaliwa na kwa kungwi nako huliwa.", "Ukipokea msaada rudi kumsaidia mwingine."),
    ("Kwa mwendawazimu kumeingia mlevi.", "Mambo yameenda vibaya zaidi."),
    ("Kwa mwoga huenda kicheko na kwa shujaa huenda kilio.", "Usifanya mambo yatakayokuingiza hatarini."),
    ("Kwea iliyo uchungu si uongo ulio mtamu.", "Ukweli mgumu ni bora kuliko uongo tamu."),
    ("Kwendako mwinyi hurudi mwinyi.", "Mambo yanayokuvutia yatakurudisha nawe."),
    ("Kwenye udongo hukosi mfinyanzi.", "Nyuso za udongo huwa na fundi mchongaji."),
    ("La kuvunda halina ubani.", "Kitu kilichoharibika hakiitaji kuvunja upya."),
    ("La mgambo likilia kuna jambo.", "Kama kuna mlio mkubwa kuna tatizo."),
    ("Leo ni leo asemaye kesho ni mwongo.", "Leo ni leo; asemaye kesho anaweza kuwa mwongo."),
    ("Lila na fila havitangamani.", "Vema na vibaya havichanganyiki."),
    ("Lililompata peku na ungo litampata.", "Kilichompata mtu mmoja kinaweza kukutokea pia."),
    ("Linalopita hupishwa.", "Kilichopita huruhusiwa kupita."),
    ("Mafiga mawili hayainjiki chungu.", "Umoja una nguvu."),
    ("Mafuu hapatilizwi.", "Mchoyo hawezi kurekebishwa."),
    ("Maisha ni bahati ifumbate.", "Maisha ni bahati; chukua nafasi yako."),
    ("Maji ukiyavulia nguo huna budi kuyaoga.", "Ukitenda jambo jiandae kwa matokeo yake."),
    ("Maji mafu mvuvi kafu.", "Mambo yanafanywa vyema kwa mazingira mazuri."),
    ("Maji ya nazi hutafuta mvungulio.", "Mambo mazuri yanatafuta nafasi."),
    ("Maji yakimwagika hayazoleki.", "MAYA yaliyopita hayalipwi tena."),
    ("Majuto ni mjukuu huja baada ya kitendo.", "Majuto huja baada ya kitendo."),
    ("Makuukuu ya mwewe si mapya ya kengewa.", "Mabaki ya tai si mapya kwa kunguru."),
    ("Mali bila daftari hupotea bila habari.", "Utajiri bila kumbukizi hupotea bila taarifa."),
    ("Mali ilivunja nguu milima ikalala.", "Utajiri hukufanya uweze mengi."),
    ("Mali ya bahili huliwa na mchwa.", "Utajiri wa mchoyo huliwa na sisimizi."),
    ("Mama mkwe hafungui mdomo.", "Mama mkwe asiposema kitu kisicho na maana."),
    ("Mambo kangaja huenda yakaja.", "Mambo mabaya yatakuja siku moja."),
    ("Mashua ya maskini huzama mtoni.", "Wazo la maskini halifikii mbali."),
    ("Maskini hana kinyongo.", "Maskini hana kiburi."),
    ("Maskini hana rafiki.", "Maskini huwa hana marafiki wa kweli."),
    ("Maskini haokoti, akiokota huambiwa keba.", "Maskini akijaribu kubadilisha hali, anashutumiwa."),
    ("Mavi usiyoyala wayawingiani kuku?", "Si vema kusumbua yaliyopita."),
    ("Mavi ya kale hayanuki.", "Mambo ya zamani hayana mvuto tena."),
    ("Mbio za sakafuni huishia ukingoni.", "Kila jambo lina mwisho."),
    ("Mbiu ya mgambo ikilia kuna jambo.", "Sauti ya tahadhari inaashiria tatizo."),
    ("Mbwa wa msasi mkali ni wakali pia.", "Mbwa wa njia kali naye ni mkali."),
    ("Mcha Mungu si mtovu.", "Mtu mtukufu si waovu."),
    ("Mchagua jembe si mkulima.", "Kuchagua zana si kuwa mfanyabiashara wa shamba."),
    ("Mchakacho ujao haulengwi na jiwe.", "Matatizo ya baadaye hayawezi kutabiriwa kwa urahisi."),
    ("Mchama ago hanyeli huenda akauya papo.", "Usudhani kuwa mtu akikusaidia hatakuhitaji baadaye; unaweza kumhitaji."),
    ("Mchawi akifichua mirimo ya wachawi huuawa.", "Mchawi anayebadilisha siri atauawa."),
    ("Mchele mmoja mapishi mbalimbali.", "Kazi inaweza kufanywa kwa njia nyingi tofauti."),
    ("Mchelea bahari si msafiri.", "Kuwaza sana huonyesha hofu ya kwenda mbali."),
    ("Mchelea mwana kulia hulia yeye.", "Kuepuka hatua muhimu kunaweza kuleta matokeo mabaya."),
    ("Mcheza hawi kiwete ngoma yataka matao.", "Mtaalamu hafanyi kazi bure; mafanikio yanahitaji juhudi."),
    ("Mchimba kisima huingia mwenyewe.", "Aliyeanza jambo ndiye wajibu wa kulimaliza."),
    ("Mchonga mwiko hukimbiza mkono wake.", "Kutendea wengine uadui kunaweza kukuathiri wewe mwenyewe."),
    ("Mchovya asali hachovyi mara moja.", "Mtu anayefurahia anataka ahurimiwa tena."),
    ("Mdomo siri ya gunda.", "Maneno yanafungua siri za mambo."),
    ("Meno ya mbwa hayaumani.", "Watu walio karibu hawapaswi kuumizana."),
    ("Mfa maji haachi kutapatatapa.", "Mtu aliyeteseka ataendelea kutafuta suluhisho."),
    ("Mficha uchi hazai.", "Aliyekataa kushirikiana matatizo hatapata suluhisho."),
    ("Mfinyanzi hulia gaeni.", "Uwezo wa mtu mara nyingi humnufaisha mwingine kuliko yeye mwenyewe."),
    ("Mgaagaa na upwa hali wali mkavu.", "Mtu anayefuata atapata."),
    ("Mganga hajigangi.", "Daktari hafanyi upasuaji kwa ajili yake mwenyewe."),
    ("Mgema akisifiwa tembo hulitia maji.", "Mtu anapoingizwa sifa hubadilika na kujiona mwenye thamani."),
    ("Mgeni njoo mwenyeji apone.", "Habari njema ni nzuri kwa kila mtu."),
    ("Mgomba haushindwi na mkunguwe.", "Mtu mwenye nguvu hana hofu kwa wengine."),
    ("Mgonjwa haulizwi dawa.", "Mtu anapoonekana hana afya, husaidiwa bila kuulizwa."),
    ("Miye nyumba ya udongo sihimili vishindo.", "Mambo dhaifu hayavumii msukumo mkubwa."),
    ("Mkaidi hafaidi hadi siku ya Iddi.", "Umakubwa haulethi faida."),
    ("Mkamia maji hayanywi.", "Mtu aliye katika hali nzuri haziitaji kutumia nafasi hiyo."),
    ("Mkata hana kinyongo.", "Maskini hana kinyongo."),
    ("Mkate mkavu wa nyumbani ni bora kuliko nyama ya shuwa ya pengine.", "Mkate mkavu wa nyumbani ni bora kuliko nyama ya mtu mwingine."),
    ("Mke ni nguo mgomba ni kupalilia.", "Mke ni muhimu kama nguo; mgomba kama zana ya kazi."),
    ("Mkokoto wa jembe si bure yao.", "Kazi ngumu inaleta thawabu."),
    ("Mkono mtupu haulambwi.", "Hodha hutokana na mkono tupu."),
    ("Mkuki kwa nguruwe mtamu kwa mwanadamu mchungu.", "Kitu kitakachompendeza mtu mmoja kinaweza kumuumiza mwingine."),
    ("Mkulima ni mmoja walaji ni wengi.", "Mfanyakazi mmoja anawafaidi wengi."),
    ("Mkwamba hauzai mzabibu.", "Mbegu mbaya haitajaza matunda mazuri."),
    ("Mkware hajiingilii mwenyewe.", "Mtu huweza kuboresha maisha yake kwa msaada wa wengine."),
    ("Mla mbuzi hulipa ngombe.", "Mtu anayefanya maovu atalipwa kwa matokeo."),
    ("Mla nawe hafi nawe ila mzaliwa nawe.", "Rafiki anaweza kukukimbia; jamaa wako atabaki."),
    ("Mlimbua nchi ni mwananchi mwenyewe.", "Watu wenye nchi ndio wanaopaswa kuisimamia."),
    ("Mnyamaa kadumbu.", "Mtu mtulivu hufanikiwa kwa uvumilivu."),
    ("Mnyonge mnyongeni haki yake mpeni.", "Saidia maskini kupata haki zao."),
    ("Mnyonge hana haki mpaka mwenye nguvu apende.", "Maskini hana haki hadi mwenye nguvu apokee kuipa."),
    ("Minyonyore haunuki hupendeza mauaye.", "Kitu kisichoonekana kizuri wakati haiwezi kuwa kizuri baadaye."),
    ("Moja shika si kumi nenda rudi.", "Ni bora kuwa na kitu kuliko kutokuwa na chochote."),
    ("Moja ya mkononi yashida mia ya mbali.", "Kile kidogo ulichonacho ni vyema kuliko mengi mbali."),
    ("Mpanda farasi wawili hupasuka msamba.", "Kujaribu kufanya kazi mbili kwa wakati mmoja huleta kushindwa."),
    ("Mpenzi hana kinyongo.", "Mpenzi hawezi kuwa na kinyongo."),
    ("Mpiga ngumi ukuta huumia mkonowe.", "Kupigana na kuta kunakuumiza wewe mwenyewe."),
    ("Mrina haogopi nyuki.", "Mtu jasiri hakuwa na hofu kwa chochote."),
    ("Msafiri kafiri.", "Msafiri ni mtu wa mbali/aliyekuja."),
    ("Mshale usio na unyoya hauendi mbali.", "Bila msaada au kinga hutaenda mbali."),
    ("Mshika mawili moja humponyoka.", "Kujaribu kushika vitu viwili hupelekea kukosa kila mmoja."),
    ("Mshonaji hachagui nguo.", "Mshonaji hawezi kuchagua mitindo aliyonayo kazi."),
    ("Msi chembe wala uta si muwani.", "Asiyekuwa tayari hawezi kufaulu."),
    ("Msitu ni mpya na komba nao.", "Bila uzoefu, utapata ugumu."),
    ("Mstahimilivu hula mbivu.", "Mvumilivu hukutana na mafanikio."),
    ("Mtafitafi hula samaki, mtulivu hula nyama.", "Mtu mtafiti anapata mengi; mtulivu anapata kila mara."),
    ("Mtaka cha mvungu ni sharti ainame.", "Mtaka kitu lazima ajitolee."),
    ("Mtaka yote hukosa yote.", "Mtaka kila kitu hatapata chochote."),
    ("Mtambua ndwele ndiye mganga.", "Yeye anayefahamu chanzo anaweza kutibu."),
    ("Mtaratibu humshinda mwenye nguvu.", "Mvumilivu huchukua nafasi juu ya mwenye nguvu."),
    ("Mtashi hana kinyongo, ajapowaswa hakomi.", "Yeye asiyeruhusu hisia kumzuia hutaachwa."),
    ("Mtembezi hula miguu yake.", "Yeye asiyetulia hatakuwa na chochote."),
    ("Mteuzi heshi tamaa.", "Mteuzi wa tamaa hawezi kufanya maamuzi mazuri."),
    ("Mti upigwa mawe ni wenye matunda.", "Wale wanaokutana na changamoto mara nyingi huvuna thawabu."),
    ("Mtoto akililia wembe mpe.", "Mtoto anayeomba anapaswa kupewa kile anahitaji."),
    ("Mtoto musikivu ndiye abarikiwaye.", "Mtoto mtulivu ni baraka."),
    ("Mtoto wa nyoka ni nyoka.", "Mwana wa mtu huwa kama mzazi."),
    ("Muamidi cha ndugu, hufa masikini.", "Kutegemea ndugu pekee kunaweza kuleta umaskini."),
    ("Mume ni kazi, mke ni nguo.", "Mume hutoa chakula; mke anajenga nyumbani."),
    ("Mume wa mama ni baba.", "Mume wa mama anapaswa kuheshimika kama baba."),
    ("Mvi usiopambwa vyema huyua.", "Mambo yasiyolimwa vizuri yatavurugika."),
    ("Mvumilivu hula mbivu.", "Uvumilivu hutoa matokeo mazuri."),
    ("Mvuvi ndiye ajuaye pweza alipo.", "Mtaalamu hajichoki kujua nyanja yake."),
    ("Mwamini Mungu si mtovu.", "Aneye Mungu hawezi kuwa mtovu."),
    ("Mwana kidonda, mjukuu kovu.", "Tatizo linaweza kuendelea kwa kizazi."),
    ("Mwana maji wa kware kufa maji mazoea.", "Yule anayezoea hatari hana hofu."),
    ("Mwana wa mhunzi asiposana hufukuta.", "Watoto wanapaswa kujifunza stadi za wazazi wao."),
    ("Mwana wa mhunzi asiposana huvuvia.", "Watoto wanapaswa kujifunza stadi za wazazi wao."),
    ("Mwanamaji hutaraji kufa maji.", "Wale wanaoishi hatarini hujua kusubiri hatari."),
    ("Mwanzo wa ngoma ni lele.", "Mambo mara nyingi huanza kwa msisimko mkubwa."),
    ("Mwanzo wa mvua ni mawingu.", "Ishara husimulia tukio linalokuja."),
    ("Mwenda juu kipungu hafikii mbinguni.", "Usiwe na malengo yasiyoweza kufikiwa."),
    ("Mwenda pole hajikwai.", "Kujitahidi kwa taratibu kunaleta mafanikio."),
    ("Mwenda tezi na omo marejeo ni ngamani.", "Yule anayekwenda mbali hatimaye atarejea, tahadhari dhidi ya kiburi."),
    ("Mwenye dada hakosi shemeji.", "Kile kina dada kinaweza kumpa shemeji."),
    ("Mwenye kelele hana neno.", "Mtu mwenye kelele hana maudhui."),
    ("Mwenye matende hana paja.", "Kuwa na kitu cha thamani kunaweza kuleta shida."),
    ("Mwenye nguvu mpishe.", "Mwingine apashe mwenye nguvu njia."),
    ("Mwili wa mwenzio ni kando ya mwilio.", "Hujui matatizo ya mtu mwingine."),
    ("Mwizi akishikwa husema kaokota.", "Mwizi akibambwa hujaribu kujielezea kwa sababu."),
    ("Mwosha huoshwa.", "Yeye anayemsaidia mwingine hupata msaada pia."),
    ("Mwosha husitiri maiti.", "Kuosha hakumsaidii marehemu."),
    ("Mzaha mzaha hutumbuka usaha.", "Kucheka kupita kiasi kunaweza kuleta shida."),
    ("Mzigo mzito mpe Mnyamwezi aubebe.", "Weka mzigo kwa mwenye uwezo kuubeba."),
    ("Mzoea kutwaa, kutoa ni bangu.", "Kuishi kwa kuchukua bila kutoa ni wizi."),
    ("Mzoea udalali hawezi kazi ya duka.", "Kuzoea hali fulani kunaweza kukuzuia kufanya kazi nyingine."),
    ("Mzoea vya kunyonga, vya kuchinja hawezi.", "Aliyezoea kitu hajui kufanya vingine vizuri."),
    ("Mzungu wa kula hafundishwi mwana.", "Aliyezoea ustawi si rahisi kumfundisha unyenyekevu."),
    ("Nahodha hodari haogopi mawimbi.", "Kiongozi mzuri hana hofu ya changamoto."),
    ("Nazi mbovu harabu ya nzima.", "Mti mbaya unaweza kuharibu kila kitu."),
    ("Ncha ikikosa mshale mzima hukosa.", "Kama ncha ikiondoka mshale hautumii kazi."),
    ("Ndaro haina neno.", "Kujivunia hakuhitaji maneno mengi."),
    ("Ndege mjanja hunaswa kwenye tundu bovu.", "Mtu mjanja anaweza kuanguka kutokana na kosa dogo."),
    ("Ndege wasiofahamu ulimbo hunaswa kumi kumi.", "Wale wasiopungua hatari wanaweza kuanguka kwa urahisi."),
    ("Ndoto njema haihadithiwi.", "Ndoto njema si bora kuzungumza."),
    ("Ndovu hashindwi na mkongawe.", "Mtu mkubwa hawezi kushindwa na mnyonge."),
    ("Ndugu chungu, jirani mkungu.", "Jamaa wa karibu anaweza kuwa hatari kuliko jirani."),
    ("Neno la mbali ni usiku wa giza.", "Ujumbe wa mbali ni kama usiku mweusi."),
    ("Ngalawa isiyo na mirengu haisalimiki.", "Mashua bila malipo hatiiwi."),
    ("Ngoja ngoja yaumiza matumbo.", "Kuchelewesha kunaweza kuumia."),
    ("Ngozi ivute ili maji.", "Fanya kabla haijaisha nafasi."),
    ("Nguo ya kuazima, haisitiri matako.", "Kitu usichomiliki hakidumu."),
    ("Ngombe haelemewi na nunduye.", "Kuwa mwajibikaji kwa wajibu wako."),
    ("Ngombe mwenye tume ndiye achinjwaye.", "Uoga huzuia heshima."),
    ("Nimekula asali udogoni, utamu ungali gegoni.", "Tamu za utotoni zikadumu kwa muda."),
    ("Njaa ya leo ni shibe ya kesho.", "Njaa ya leo inaweza kuleta shibe kesho."),
    ("Njia ya mwongo ni fupi.", "Njia ya mwongo ni haraka lakini si ya kudumu."),
    ("Nyani haoni kundule, huliona la mwenziwe.", "Mjinga haioni dosari yake mwenyewe, anaona ya wengine."),
    ("Nyota ya mtu kuzimika.", "Nyota ya mtu inaweza kuzimika."),
    ("Nyumba ya mgumba haina kilio.", "Nyumba ya mwanamke bila watoto hakuna mlio wa watoto."),
    ("Nyumba ya udongo haihimili kishindo.", "Nyumba ya udongo haiwezi kuhimili msukumo mkubwa."),
    ("Nzi kufa juu ya kidonda si haramu.", "Nzi kufa juu ya jeraha sio kosa."),
    ("Ondoa dari, uezeke paa.", "Ondoa vizingiti na ujenge upya."),
    ("Oto la kuku usilaze kicheche.", "Usimtrust kwa urahisi watu kuhusu mali zako."),
    ("Pahala pa itifaki ikirahi haipiti.", "Sehemu yenye makubaliano haikosi amani."),
    ("Paka akiondoka panya hujitawala.", "Wakati hakuna mamlaka watu watajiamulia wenyewe."),
    ("Paka akiondoka panya hutawala.", "Wakati hakuna anayehusika watu watatoa matendo yao wenyewe."),
    ("Paka hakubali kulala chali.", "Usikubali kufanya kitu kisichofaa kwa tamaduni zako."),
    ("Paka mafuta kwa mgongo wa chupa.", "Kujiita mlaghai (kusema uongo)."),
    ("Palilia mkoche, mnazi wende na nyasi.", "Panga vipaumbele vizuri."),
    ("Pambo la jeneza lamfaani mtu?", "Kipambe si kitakachomsaidia mtu wakati wa shida."),
    ("Panapo udhiapenyeza rupia.", "Kama palipo tatizo kutakuwa na njia."),
    ("Papo kwa papo kamba hukata jiwe.", "Katika changamoto, vumilia hadi upate mafanikio."),
    ("Pato kuu ni la Mungu apaye wawi na wema.", "Mapato makuu ni zawadi kutoka kwa Mungu."),
    ("Pema ijapo pema, ukipema sana si pema tena.", "Ukizidi ukifanya vizuri, inaweza kuwa vibaya."),
    ("Pembe za chaki.", "Sehemu za kibinafsi."),
    ("Penye nia pana njia.", "Ambapo kuna nia kuna njia."),
    ("Penye uchafu hapakosi nzi.", "Mahali pa uchafu panavutia nzi."),
    ("Pilipili usiyoila yakuwashia nini?", "Unaomuaja kwa mambo usiyo hayo?"),
    ("Pilipili iliyo shambani, yakuwashiani?", "Kwa nini uzungumzie mambo ambayo hayajatokea?"),
    ("Pitapita zake hazininyimi usingizi.", "Matendo yao hayandidhi usingizi wangu."),
    ("Polepole ndiyo mwendo.", "Polepole ni njia sahihi; uvumilivu ni muhimu."),
    ("Punda haendi ila kwa mikwaju.", "Watu wengine hushughulika tu kwa nguvu."),
    ("Radhi ni bora kuliko mali.", "Kutoridhika ni bora kuliko utajiri."),
    ("Rahisi haihalisi.", "Rahisi sio daima halisi (rahisi huenda haraka)."),
    ("Samaki mkunje angali mbichi, akishakauka hakunjiki.", "Fanya mabadiliko mapema kabla havijaanza kuwa vigumu."),
    ("Samaki mmoja aki huoza wote wameoza.", "Iwapo mmoja ameanza kuharibika, wengine pia huathiriwa."),
    ("Shauku huondoa maarifa.", "Msukumo mwingi unaweza kuondoa busara au maarifa."),
    ("Sheria ni msumeno hukata huku na huku.", "Sheria ina pande mbili; inaweza kumkata mbele na nyuma."),
    ("Sheria ni msumeno hukata mbele na nyuma.", "Sheria ina pande mbili; inaweza kumkata mbele na nyuma."),
    ("Shetani wa mtu ni mtu.", "Shetani wa mtu ni watu wengine."),
    ("Shibe ni mwana malevya na njaa ni mwana malegeza.", "Kuziba tamaa kunasababisha uvivu; njaa huleta harakati."),
    ("Shukurani ya punda ni mateke.", "Shukrani za punda zinaweza kuwa za kurtukia."),
    ("Sikio la kufa halisikii dawa.", "Baadhi ya watu hawapendi kusikiliza ushauri."),
    ("Siku njema huonekana asubuhi.", "Siku njema inaonekana tangu asubuhi."), 
    ("Siri ya mtungi aijuaye kata.", "Ujuavyo jambo mpaka ukaipitia mwenyewe."),
    ("Siri ya kaburi aijuaye maiti.", "Siri ya kaburi inajulikana na mwenye kufariki."),
    ("Sisimizi hawi ngombe.", "Kibonge hawezi kuwa ng'ombe."),
    ("Sitafuga ndwele na waganga tele.", "Usificha ugonjwa wakati kuna wataalamu."),
    ("Subira yavuta heri.", "Uvumilivu huvuta baraka."),
    ("Taa haachi mwiba awe.", "Hakikisha tahadhari hata baada ya mafanikio."),
    ("Tabia ya mtu kupenda mambo ya anasa na starehe.", "Watu wana tabia ya kupenda anasa na starehe."),
    ("Tikiti baya liko shambani mwako.", "Kuna matatizo yako mwenyewe ya kushughulikia."),
    ("Titi la mama li tamu, jingine haliishi hamu.", "Ridhika na kile ulichopewa."),
    ("Tone na tone huwa mchirizi.", "Jitihada za mara kwa mara huleta mafanikio."),
    ("Tupa jongoo na mti wake.", "Shughulikia tatizo kwenye chanzo chake."),
    ("Turufu huenda kwa mchezaji.", "Mwenye udhibiti ananufaika."),
    ("Ubaya hatima yake mbaya.", "Uovu mwisho wake ni mbaya."),
    ("Ubishi chanzo cha mateto.", "Mjadala huleta migogoro."),
    ("Uchungu wa mwana aujuaye mzazi.", "Mzazi ndiye ajuaye uchungu wa mtoto."),
    ("Udogo wa kimo una mambo.", "Ukubwa mdogo pia una faida zake."),
    ("Ufukara hufanya mtu awe na udhalili moyoni.", "Umasikini huvutia unyenyekevu moyoni."),
    ("Uhalifu mwenenzi si wa mkazi milele.", "Mshirika wa uhalifu si wa kudumu."),
    ("Uhenga hauambiwi maana.", "Si busara kumwambia mwingine makosa ya zamani."),
    ("Uislamu umemshinda fisi.", "Nguvu na haki hutuongoza kushinda mabaya."),
    ("Ujana ni moshi ukienda haurudi.", "Ujana ni kama moshi, haurejei; tumia vizuri."),
    ("Ujanja mwingi mbele giza.", "Ujanja mwingi unaweza kupelekea giza au woga."),
    ("Ukiiga tembo kunya utapasuka msamba.", "Kujifanya mkubwa kupita kiasi kutakuumiza."),
    ("Uking’wafua mnofu ukumbuke na kuguguna mfupa.", "Ukitumia mengi, kumbuka pia ile sehemu ndogo."),
    ("Ukiona ambari na zinduna i papo.", "Tambua fursa unapoiona."),
    ("Ukiona ambari, zinduna ipapo.", "Ukiona kitu cha thamani kuna zaidi karibu."),
    ("Ukiona vyaelea vimeundwa.", "Hakuna kinachotokea bila juhudi."),
    ("Ukipenda chongo huita kengeza.", "Watu hucheka kile wanachotaka."),
    ("Ukistaajabu ya Musa utayaona ya firauni.", "Utashangazwa zaidi ukiona mengi."),
    ("Ukitaja nyoka shika kigongo.", "Tahadhari unapotoa maneno; inaweza kuvutia matatizo."),
    ("Ukitaka kujua utamu wangoma ingia ucheze.", "Ili ujue ladha ya asali lazima uionje mwenyewe."),
    ("Ukitaka kuruka, agana na nyonga.", "Kukwepa hatari ya kuruka, jiandae kuchukua hatari."),
    ("Ukitaka riba sikio ziba.", "Kama huwezi kusikia, ibwaga tu."),
    ("Ukitenda wema usingoje kulipwa.", "Fanya wema bila kutegemea malipo."),
    ("Ukubwa ni jaa.", "Ukubwa ni mzigo."),
    ("Ukubwa wa pua si wingi wa kamasi.", "Muonekano hauwezi kuwakilisha wingi wa kitu."),
    ("Ukuukuu wa kamba si upya wa ukambaa.", "Uzoefu ni muhimu kuliko ujana."),
    ("Ukweli ukidhihiri uongo hujitenga.", "Ukweli utawatafuta waongo."),
    ("Ulimi hauna mfupa.", "Maneno yanaweza kuumiza sana."),
    ("Ulimwengu ni dhaifu siuoneni sheshe.", "Dunia ni dhaifu; itunzwe na isivutie mambo ya muda."),
    ("Umoja ni nguvu utengano ni udhaifu.", "Umoja ni nguvu, mgawanyiko ni udhaifu."),
    ("Upeo wa macho si mwisho wa dunia.", "Kuna kila mara zaidi ya unavyoona."),
    ("Ushikwapo shikamana.", "Wakati wa shida shikamana."),
    ("Usiache mbachao kwa msala upitao.", "Usiachi ndoto zako kwa kitu cha muda."),
    ("Usidharau dafu embe ni tunda la msimu.", "Usiudharau kitu kwa sababu si maarufu sasa."),
    ("Usidharau kiserema chalima kuliko jembe zima.", "Usidharau kitu kwa ukubwa au umbo."),
    ("Usicheze na simba ukamtia mkono kinywani.", "Usijaribu kumtisha mwenye nguvu."),
    ("Usigombe na mkwezi, nazi imeliwa na mwezi.", "Usigombe na mtu asiyekufanya vibaya."),
    ("Usikate ubeleko mtoto kabla hajazaliwa.", "Usihesabu mapema mafanikio mpaka yafikike."),
    ("Usimlaumu udobi kaniki ni rangi yake.", "Usimlaumu mtu kwa asili yake."),
    ("Usimwage mtama kwenye kuku wengi.", "Usipoteze muda wako kwa mambo yasiyostahili."),
    ("Usinipake mafuta kwa mgongo wa chupa.", "Usinifanye mchekeshaji."),
    ("Usinivishe kilemba cha ukoka.", "Usinipa matarajio ya uongo."),
    ("Usione tanga la nguo ukasahau la myaa.", "Usikwepe kuona mambo makubwa kwa kuangalia madogo."),
    ("Usipoziba ufa utajenga ukuta.", "Usipotatua tatizo dogo litakua kubwa."),
    ("Utajiri ni kivuli.", "Utajiri ni kivuli; si cha kudumu."),
    ("Uuzohali ni nyumba ya njaa.", "Uzembe huleta umaskini."),
    ("Uzuri wa mkakasi ndani kipande cha mti.", "Uzuri wa nje unaweza kuwa bila maadili ya ndani."),
    ("Uzuri wa mkakasi ukilowa maji basi.", "Usiruhusu uzuri wa nje ukudanganye."),
    ("Vita vya panzi, furaha ya kunguru.", "Mgogoro kati ya wadogo hufanikiwa kwa upande wa tatu."),
    ("Vundo la kinyesi ni malazi ya paka/bata.", "Baadhi wanapendezwa na mazingira yasiyofaa."),
    ("Vunja dari uezeke paa.", "Wekeza katika maboresho na maendeleo."),
    ("Wajua tamu ya ua, sumu wanipeani?", "Unajua kitakachoumiza mwingine; usifanye."),
    ("Wanja wa manga si dawa ya chongo.", "Suluhisho la superficial si tiba halisi."),
    ("Wapiga mbiu ganjoni utasikiwa na nani?", "Kuzungumza mahali pasipo na wasikilizaji ni kuchang wasting."),
    ("Waraka ni nusu ya kuonana.", "Mawasiliano ni muhimu hata isipo kuwa ana kwa ana."),
    ("Wema hauozi.", "Kazi nzuri hazisahauwi."),
    ("Werevu mwingi mbele giza.", "Uwerevu kupita kiasi unaweza kuleta taabu."),
    ("Ya Kaizari mpe Kaizari na ya Mungu mpe Mungu.", "Mpe Kaizari anachomlima Kaizari, na Mpe Mungu anachomlima Mungu."),
    ("Ya mgambo ikilia kuna jambo.", "Ishara ya tahadhari inaonyesha tatizo."),
    ("Ya mkiwa haiiti na ikiita hupapata.", "Biashara ya maskini mara nyingi haina faida; ikifaidi ni kwa bahati."),
    ("Ya mkiwa haiiti, na ikiita hupapa.", "Biashara ya maskini mara nyingi haina faida; ikifaidi ni kwa bahati."),
    ("Yaliyompata peku na ungo yatampata.", "Kilichompata mtu mmoja kinaweza kukutokea pia."),
    ("Yaliyopita si ndwele tugange yajayo.", "Usikaa ukazia yaliyopita; jifunze na uende mbele."),
    ("Yaliyopita si uele tugange yajayo.", "Usibaki kwenye yaliyopita; jifunze kwa ajili ya yajayo."),
    ("Yuajifanya mawele, kujitia mitini, ili aambiwe naye yumo.", "Anajifanya kuiga wengine ili apokelewe kama mmoja wao."),
    ("Zana za vita ni silaha.", "Zana za vita ni silaha.")
]

# Build dataset texts in Kiswahili: keep the original proverb and use the translated Kiswahili explanation
texts = [f"Methali: {swahili}\nMaelezo: {kiswahili_explanation}" for swahili, kiswahili_explanation in pairs]

dataset = Dataset.from_dict({"text": texts})

tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True, max_length=128)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

tokenized_datasets = tokenized_datasets.train_test_split(test_size=0.2)

train_dataset = tokenized_datasets["train"]
eval_dataset = tokenized_datasets["test"]

model = GPT2LMHeadModel.from_pretrained("gpt2")

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

training_args = TrainingArguments(
    output_dir='./results',
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    num_train_epochs=3,
    weight_decay=0.01,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    data_collator=data_collator,
)

trainer.train()

trainer.save_model("./fine_tuned_gpt2")
tokenizer.save_pretrained("./fine_tuned_gpt2")
