from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-multilingual-cased")

proverbs = [
"Ada ya mja hunena muungwana ni kitendo.",
"Adhabu ya kaburi aijuaye maiti.",
"Adui wa mtu ni mtu, adui mpende, adui aangukapo mnyanyue.",
"Afadhali ya Musa kuliko ya Firauni.",
"Afya ni bora kuliko mali.",
"Ahadi ni deni.",
"Aibu ya maiti aijuaye mwosha.",
"Aisifuye mvua imemnyea.",
"Alisifuye jua limemwangaza.",
"Ajali haina kinga.",
"Ajizi ni nyumba ya njaa.",
"Akiba halozi, akiba si mbi ijapokuwa ya kumbi, siku ya kivumbi hutiwa motoni.",
"Akili ni mali, akili nyingi huondoa maarifa.",
"Akili ni nywele kila mtu ana zake.",
"Akili nyingi huondoa maarifa.",
"Akufaaye kwa dhiki ndiye rafiki.",
"Akutendaye mtende, mche asiyekutenda.",
"Aliye juu mngoje chini.",
"Aliye kando haangukiwi na mti.",
"Aliyekula kitovu chako hatakuachia utumbo.",
"Aliyekunyima kunde/mbaazi amekupungunguzia mashuzi.",
"Aliyekunyoa shungi kakupunguzia kuchana.",
"Aliyetota hajui kutota.",
"Aliyeumawa na nyoka akiona unyasi hushituka.",
"Amani haipatikani ila kwa ncha ya upanga.",
"Amnyimaye punda adesi ampunguzia mashuzi.",
"Anayemwamini Mungu si mtovu.",
"Angalipaa juu kipungu kamwe hafiki mbinguni.",
"Angurumapo Simba, mcheza nani?",
"Asio mali, hasidi wa mwenye mali.",
"Asiye na bahati habahatiki.",
"Asiye na mwana aeleke jiwe.",
"Asiyejua utu si mtu.",
"Asiyekubali kushindwa si mshindani.",
"Asiyesafiri husifu upishi wa mama yake tu.",
"Asiyesikia la mkuu huvunjika guu.",
"Atangaye na jua hujua.",
"Avumaye baharini papa kumbe wengine wapo.",
"Awali ni awali hakuna awali mbovu.",
"Baada ya dhiki faraja.",
"Bahati ya mwenzio usiilalie mlango wazi.",
"Balaa hukutia mtu wako.",
"Bandu bandu humaliza gogo.",
"Baniani mbaya kiatu chake dawa.",
"Bao nene si chuma chembamba.",
"Barua ya moyo husomwa juu ya panda la uso.",
"Bendera hufuata upepo.",
"Bilashi, bilashi, katu haitoshi.",
"Binadamu ni kama kilihafu hakosi uchafu.",
"Bura yangu sibadili kwa rehani.",
"Chanda chema huvikwa pete.",
"Chelewa chelewa, utakuta mwana si wako.",
"Chombo kilichopikiwa samaki hakiachi kunuka vumba.",
"Chovya chovya humaliza buyu la asali.",
"Chungu kidogo huchemka upesi.",
"Chururu si ndondondo.",
"Dalili ya mvua ni mawingu.",
"Damu ni nzito kuliko maji.",
"Dau la mnyonge haliendi joshi likienda joshi ni matakwa ya Mungu.",
"Dawa ya deni kulipa.",
"Dawa ya jipu kulipasua.",
"Dawa ya moto ni moto.",
"Debe shinda haliachi kutika.",
"Debe tupu haliachi kuvuma.",
"Domo kaya samli kwa mwenye ngombe.",
"Dondandugu halina dawa.",
"Dua la kuku halimpati mwewe.",
"Dunia hadaa ulimwengu shujaa.",
"Eda ni ada yenye faida.",
"Fadhila mpe mama na Mola atakubariki.",
"Fadhila za punda mashuzi.",
"Fadhili ukitenda usingoje shukrani.",
"Fahari isiyo na ari haina heri.",
"Fimbo ya mbali haiuwi nyoka.",
"Fumbo mfumbie mjinga mwerevu huling’amua.",
"Funika kombe mwanaharamu apite.",
"Ganda la muwa la jana chungu kaona kivuno.",
"Ghururi na binadamu hawaachani.",
"Ghushi dhahabu na shaba dhambi na dhawabu havighushiki.",
"Haba na haba hujaza kibaba.",
"Hadhari kabla ya hatari.",
"Hakuna bamvua lisilo usubi.",
"Hakuna marefu yasiyokuwa na ncha.",
"Hakuna masika yasiyokuwa na mbu.",
"Hakuna ziada mbovu.",
"Hamadi kibindo ni silaha iliyo mkononi.",
"Hapana maji yasiyo na mawimbi.",
"Haraka haraka haina baraka.",
"Hasira hasara.",
"Hasira ya mkizi furahaya mvuvi.",
"Hatua moja hufupisha safari.",
"Heri kujikwaa kidole kuliko ulimi.",
"Heri mchawi kuliko mtu fitina.",
"Heri nusu shari kuliko shari kamili.",
"Hewala! si utumwa.",
"Hindi ndiko kwenye nguo na wendao uchi wako.",
"Huenda umaskini ukakaribia ukafiri.",
"Hukutia mtu wako.",
"Ibilisi wa mtu ni mtu.",
"Ingiwa na shake.",
"Inuka twende ni kwa waaganao.",
"Ivushayo ni mbovu.",
"Jambo la ukucha halichukuliwi shoka.",
"Jaribu huleta fanaka.",
"Jawabu la kesho andaa leo.",
"Jawabu wakatiwe na wakatiwe si zani.",
"Jimbi wa shamba hawiki mjini.",
"Jino likingoka ukubwani halimei tena.",
"Jogoo likiwika lisiwikae kutakucha.",
"Jogoo wa shamba hawiki mjini.",
"Kafiri akufaaye si Islamu asiyekufaa.",
"Kamba hukatikia pabovu.",
"Katakata pua uunge wajihi.",
"Katiti ni tamu kingi kina kiembeza.",
"Kazi mbi si mchezo mwema.",
"Kenda fumbata si kumi nenda uje kesho.",
"Kichwa cha kuku hakihimili kilemba.",
"Kidole kimoja hakivunji chawa.",
"Kifo cha wengi harusi.",
"Kila mtoto na koja lake.",
"Kila mwacha samboye, huenda ali mwanamaji.",
"Kila mwamba ngoma,huvutia kwake.",
"Kila mwamba ngoma, ngozi huivuta kwake.",
"Kila ndege huruka kwa ubawa wake.",
"Kilichoingia mjini si haramu.",
"Kilimia kikizama kwa jua huzuka kwa mvua, kikizama kwa mvua huzuka kwa jua.",
"Kimya kingi kina mshindo mkuu.",
"Kinyozi hajinyoi akinyoa kujikata.",
"Kinywa ni jumba la maneno.",
"Kipya kinyemi ingawa kidondo.",
"Kisebusebu na kiroho ki papo.",
"Kitanda usicholala huwajui kunguni wake.",
"Kitegwacho kukitega kwataka ubongo.",
"Kivuli cha mgude husaidia walio mbali.",
"Kujikwaa si kuanguka, bali ni kwenda mbele.",
"Kukopa harusi kulipa matanga.",
"Kuku havunji yai lake.",
"Kuku mgeni zawadi za kunguru.",
"Kula kutamu kulima mavune.",
"Kula ni vyepesi lakini kulima ngo.",
"Kula uhondo kwataka matendo.",
"Kulea mimba si kazi kazi kulea mwana.",
"Kunguru mwoga hukimbiza bawa lake.",
"Kutoa ni moyo si utajiri.",
"Kutoa ni moyo usambe ni utajiri.",
"Kuvua si kazi kazi ni magawioni.",
"Kuvuja kwa pakacha nafuu kwa mchukuzi.",
"Kuzima koleo si mwisho wa uhunzi.",
"Kwa mwari kwaliwa na kwa kungwi nako huliwa.",
"Kwa mwendawazimu kumeingia mlevi.",
"Kwa mwoga huenda kicheko na kwa shujaa huenda kilio.",
"Kwea iliyo uchungu si uongo ulio mtamu.",
"Kwendako mwinyi hurudi mwinyi.",
"Kwenye udongo hukosi mfinyanzi.",
"La kuvunda halina ubani.",
"La mgambo likilia kuna jambo.",
"Leo ni leo asemaye kesho ni mwongo.",
"Lila na fila havitangamani.",
"Lililompata peku na ungo litampata.",
"Linalopita hupishwa.",
"Mafiga mawili hayainjiki chungu.",
"Mafuu hapatilizwi.",
"Maisha ni bahati ifumbate.",
"Maji ukiyavulia nguo huna budi kuyaoga.",
"Maji mafu mvuvi kafu.",
"Maji ya nazi hutafuta mvungulio.",
"Maji yakimwagika hayazoleki.",
"Majuto ni mjukuu huja baada ya kitendo.",
"Makuukuu ya mwewe si mapya ya kengewa.",
"Mali bila daftari hupotea bila habari.",
"Mali ilivunja nguu milima ikalala.",
"Mali ya bahili huliwa na mchwa.",
"Mama mkwe hafungui mdomo.",
"Mambo kangaja huenda yakaja.",
"Mashua ya maskini huzama mtoni.",
"Maskini hana kinyongo.",
"Maskini hana rafiki.",
"Maskini haokoti, akiokota huambiwa keba.",
"Mavi usiyoyala wayawingiani kuku?",
"Mavi ya kale hayanuki.",
"Mbio za sakafuni huishia ukingoni.",
"Mbiu ya mgambo ikilia kuna jambo.",
"Mbwa wa msasi mkali ni wakali pia.",
"Mcha Mungu si mtovu.",
"Mchagua jembe si mkulima.",
"Mchakacho ujao haulengwi na jiwe.",
"Mchama ago hanyeli huenda akauya papo.",
"Mchawi akifichua mirimo ya wachawi huuawa.",
"Mchele mmoja mapishi mbalimbali.",
"Mchelea bahari si msafiri.",
"Mchelea mwana kulia hulia yeye.",
"Mcheza hawi kiwete ngoma yataka matao.",
"Mchimba kisima huingia mwenyewe.",
"Mchonga mwiko hukimbiza mkono wake.",
"Mchovya asali hachovyi mara moja.",
"Mdomo siri ya gunda.",
"Meno ya mbwa hayaumani.",
"Mfa maji haachi kutapatatapa.",
"Mficha uchi hazai.",
"Mfinyanzi hulia gaeni.",
"Mgaagaa na upwa hali wali mkavu.",
"Mganga hajigangi.",
"Mgema akisifiwa tembo hulitia maji.",
"Mgeni njoo mwenyeji apone.",
"Mgomba haushindwi na mkunguwe.",
"Mgonjwa haulizwi dawa.",
"Miye nyumba ya udongo sihimili vishindo.",
"Mkaidi hafaidi hadi siku ya Iddi.",
"Mkamia maji hayanywi.",
"Mkata hana kinyongo.",
"Mkate mkavu wa nyumbani ni bora kuliko nyama ya shuwa ya pengine.",
"Mke ni nguo mgomba ni kupalilia.",
"Mkokoto wa jembe si bure yao.",
"Mkono mtupu haulambwi.",
"Mkuki kwa nguruwe mtamu kwa mwanadamu mchungu.",
"Mkulima ni mmoja walaji ni wengi.",
"Mkwamba hauzai mzabibu.",
"Mkware hajiingilii mwenyewe.",
"Mla mbuzi hulipa ngombe.",
"Mla nawe hafi nawe ila mzaliwa nawe.",
"Mlimbua nchi ni mwananchi mwenyewe.",
"Mnyamaa kadumbu.",
"Mnyonge mnyongeni haki yake mpeni.",
"Mnyonge hana haki mpaka mwenye nguvu apende.",
"Minyonyore haunuki hupendeza mauaye.",
"Moja shika si kumi nenda rudi.",
"Moja ya mkononi yashida mia ya mbali.",
"Mpanda farasi wawili hupasuka msamba.",
"Mpenzi hana kinyongo.",
"Mpiga ngumi ukuta huumia mkonowe.",
"Mrina haogopi nyuki.",
"Msafiri kafiri.",
"Mshale usio na unyoya hauendi mbali.",
"Mshika mawili moja humponyoka.",
"Mshonaji hachagui nguo.",
"Msi chembe wala uta si muwani.",
"Msitu ni mpya na komba nao.",
"Mstahimilivu hula mbivu.",
"Mtafitafi hula samaki, mtulivu hula nyama.",
"Mtaka cha mvungu ni sharti ainame.",
"Mtaka yote hukosa yote.",
"Mtambua ndwele ndiye mganga.",
"Mtaratibu humshinda mwenye nguvu.",
"Mtashi hana kinyongo, ajapowaswa hakomi.",
"Mtembezi hula miguu yake.",
"Mteuzi heshi tamaa.",
"Mti upigwao mawe ni wenye matunda.",
"Mtoto akililia wembe mpe.",
"Mtoto musikivu ndiye abarikiwaye.",
"Mtoto wa nyoka ni nyoka.",
"Muamidi cha ndugu, hufa masikini.",
"Mume ni kazi, mke ni nguo.",
"Mume wa mama ni baba.",
"Mvi usiopambwa vyema huyua.",
"Mvumilivu hula mbivu.",
"Mvuvi ndiye ajuaye pweza alipo.",
"Mwamini Mungu si mtovu.",
"Mwana kidonda, mjukuu kovu.",
"Mwana maji wa kware kufa maji mazoea.",
"Mwana wa mhunzi asiposana hufukuta.",
"Mwana wa mhunzi asiposana huvuvia.",
"Mwanamaji hutaraji kufa maji.",
"Mwanzo wa ngoma ni lele.",
"Mwanzo wa mvua ni mawingu.",
"Mwenda juu kipungu hafikii mbinguni.",
"Mwenda pole hajikwai.",
"Mwenda tezi na omo marejeo ni ngamani.",
"Mwenye dada hakosi shemeji.",
"Mwenye kelele hana neno.",
"Mwenye matende hana paja.",
"Mwenye nguvu mpishe.",
"Mwili wa mwenzio ni kando ya mwilio.",
"Mwizi akishikwa husema kaokota.",
"Mwosha huoshwa.",
"Mwosha husitiri maiti.",
"Mzaha mzaha hutumbuka usaha.",
"Mzigo mzito mpe Mnyamwezi aubebe.",
"Mzoea kutwaa, kutoa ni bangu.",
"Mzoea udalali hawezi kazi ya duka.",
"Mzoea vya kunyonga, vya kuchinja hawezi.",
"Mzungu wa kula hafundishwi mwana.",
"Nahodha hodari haogopi mawimbi.",
"Nazi mbovu harabu ya nzima.",
"Ncha ikikosa mshale mzima hukosa.",
"Ndaro haina neno.",
"Ndege mjanja hunaswa kwenye tundu bovu.",
"Ndege wasiofahamu ulimbo hunaswa kumi kumi.",
"Ndoto njema haihadithiwi.",
"Ndovu hashindwi na mkongawe.",
"Ndugu chungu, jirani mkungu.",
"Neno la mbali ni usiku wa giza.",
"Ngalawa isiyo na mirengu haisalimiki.",
"Ngoja ngoja yaumiza matumbo.",
"Ngozi ivute ili maji.",
"Nguo ya kuazima, haisitiri matako.",
"Ngombe haelemewi na nunduye.",
"Ngombe mwenye tume ndiye achinjwaye.",
"Nimekula asali udogoni, utamu ungali gegoni.",
"Njaa ya leo ni shibe ya kesho.",
"Njia ya mwongo ni fupi.",
"Nyani haoni kundule, huliona la mwenziwe.",
"Nyota ya mtu kuzimika.",
"Nyumba ya mgumba haina kilio.",
"Nyumba ya udongo haihimili kishindo.",
"Nzi kufa juu ya kidonda si haramu.",
"Ondoa dari, uezeke paa.",
"Oto la kuku usilaze kicheche.",
"Pahala pa itifaki ikirahi haipiti.",
"Paka akiondoka panya hujitawala.",
"Paka akiondoka panya hutawala.",
"Paka hakubali kulala chali.",
"Paka mafuta kwa mgongo wa chupa.",
"Palilia mkoche, mnazi wende na nyasi.",
"Pambo la jeneza lamfaani mtu?",
"Panapo udhiapenyeza rupia.",
"Papo kwa papo kamba hukata jiwe.",
"Pato kuu ni la Mungu apaye wawi na wema.",
"Pema ijapo pema, ukipema sana si pema tena.",
"Pembe za chaki.",
"Penye nia pana njia.",
"Penye uchafu hapakosi nzi.",
"Pilipili usiyoila yakuwashia nini?",
"Pilipili iliyo shambani, yakuwashiani?",
"Pitapita zake hazininyimi usingizi.",
"Polepole ndiyo mwendo.",
"Punda haendi ila kwa mikwaju.",
"Radhi ni bora kuliko mali.",
"Rahisi haihalisi.",
"Samaki mkunje angali mbichi, akishakauka hakunjiki.",
"Samaki mmoja aki huoza wote wameoza.",
"Shauku huondoa maarifa.",
"Sheria ni msumeno hukata huku na huku.",
"Sheria ni msumeno hukata mbele na nyuma.",
"Shetani wa mtu ni mtu.",
"Shibe ni mwana malevya na njaa ni mwana malegeza.",
"Shukurani ya punda ni mateke.",
"Sikio la kufa halisikii dawa.",
"Siku njema huonekana asubuhi.",
"Siri ya mtungi aijuaye kata.",
"Siri ya kaburi aijuaye maiti.",
"Sisimizi hawi ngombe.",
"Sitafuga ndwele na waganga tele.",
"Subira yavuta heri.",
"Taa haachi mwiba awe.",
"Tabia ya mtu kupenda mambo ya anasa na starehe.",
"Tikiti baya liko shambani mwako.",
"Titi la mama li tamu, jingine haliishi hamu.",
"Tone na tone huwa mchirizi.",
"Tupa jongoo na mti wake.",
"Turufu huenda kwa mchezaji.",
"Ubaya hatima yake mbaya.",
"Ubishi chanzo cha mateto.",
"Uchungu wa mwana aujuaye mzazi.",
"Udogo wa kimo una mambo.",
"Ufukara hufanya mtu awe na udhalili moyoni.",
"Uhalifu mwenenzi si wa mkazi milele.",
"Uhenga hauambiwi maana.",
"Uislamu umemshinda fisi.",
"Ujana ni moshi ukienda haurudi.",
"Ujanja mwingi mbele giza.",
"Ukiiga tembo kunya utapasuka msamba.",
"Uking’wafua mnofu ukumbuke na kuguguna mfupa.",
"Ukiona ambari na zinduna i papo.",
"Ukiona ambari, zinduna ipapo.",
"Ukiona vyaelea vimeundwa.",
"Ukipenda chongo huita kengeza.",
"Ukistaajabu ya Musa utayaona ya firauni.",
"Ukitaja nyoka shika kigongo.",
"Ukitaka kujua utamu wangoma ingia ucheze.",
"Ukitaka kuruka, agana na nyonga.",
"Ukitaka riba sikio ziba.",
"Ukitenda wema usingoje kulipwa.",
"Ukubwa ni jaa.",
"Ukubwa wa pua si wingi wa kamasi.",
"Ukuukuu wa kamba si upya wa ukambaa.",
"Ukweli ukidhihiri uongo hujitenga.",
"Ulimi hauna mfupa.",
"Ulimwengu ni dhaifu siuoneni sheshe.",
"Umoja ni nguvu utengano ni udhaifu.",
"Upeo wa macho si mwisho wa dunia.",
"Ushikwapo shikamana.",
"Usiache mbachao kwa msala upitao.",
"Usidharau dafu embe ni tunda la msimu.",
"Usidharau kiserema chalima kuliko jembe zima.",
"Usicheze na simba ukamtia mkono kinywani.",
"Usigombe na mkwezi, nazi imeliwa na mwezi.",
"Usikate ubeleko mtoto kabla hajazaliwa.",
"Usimlaumu udobi kaniki ni rangi yake.",
"Usimwage mtama kwenye kuku wengi.",
"Usinipake mafuta kwa mgongo wa chupa.",
"Usinivishe kilemba cha ukoka.",
"Usione tanga la nguo ukasahau la myaa.",
"Usipoziba ufa utajenga ukuta.",
"Utajiri ni kivuli.",
"Uuzohali ni nyumba ya njaa.",
"Uzuri wa mkakasi ndani kipande cha mti.",
"Uzuri wa mkakasi ukilowa maji basi.",
"Vita vya panzi, furaha ya kunguru.",
"Vundo la kinyesi ni malazi ya paka/bata.",
"Vunja dari uezeke paa.",
"Wajua tamu ya ua, sumu wanipeani?",
"Wanja wa manga si dawa ya chongo.",
"Wapiga mbiu ganjoni utasikiwa na nani?",
"Waraka ni nusu ya kuonana.",
"Wema hauozi.",
"Werevu mwingi mbele giza.",
"Ya Kaizari mpe Kaizari na ya Mungu mpe Mungu.",
"Ya mgambo ikilia kuna jambo.",
"Ya mkiwa haiiti na ikiita hupapata.",
"Ya mkiwa haiiti, na ikiita hupapa.",
"Yaliyompata peku na ungo yatampata.",
"Yaliyopita si ndwele tugange yajayo.",
"Yaliyopita si uele tugange yajayo.",
"Yuajifanya mawele, kujitia mitini, ili aambiwe naye yumo.",
"Zana za vita ni silaha."
]

for text in proverbs:
    tokens = tokenizer.tokenize(text)
    print(tokens)
